### ISSUE TITLE
where to find these files?

### ISSUE THREAD

**Issue by BEAST-Community** [BernardoGG/SARS-CoV-2_Genomic_lineages_Ecuador#3]
meta1 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_15_(1).tsv", sep = "\t", strip.white = TRUE)
meta2 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_15_(2).tsv", sep = "\t", strip.white = TRUE)
meta3 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_15_(3).tsv", sep = "\t", strip.white = TRUE)
meta4 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(4).tsv", sep = "\t", strip.white = TRUE)
meta5 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(5).tsv", sep = "\t", strip.white = TRUE)
meta6 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(6).tsv", sep = "\t", strip.white = TRUE)
meta7 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(7).tsv", sep = "\t", strip.white = TRUE)
meta8 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(8).tsv", sep = "\t", strip.white = TRUE)
meta9 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(9).tsv", sep = "\t", strip.white = TRUE)
meta10 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(10).tsv", sep = "\t", strip.white = TRUE)
meta11 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(11).tsv", sep = "\t", strip.white = TRUE)
meta12 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(12).tsv", sep = "\t", strip.white = TRUE)
meta13 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(13).tsv", sep = "\t", strip.white = TRUE)
meta14 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(14).tsv", sep = "\t", strip.white = TRUE)
meta15 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(15).tsv", sep = "\t", strip.white = TRUE)
meta16 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(16).tsv", sep = "\t", strip.white = TRUE)
meta17 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(17).tsv", sep = "\t", strip.white = TRUE)
meta18 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(18).tsv", sep = "\t", strip.white = TRUE)
meta19 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(19).tsv", sep = "\t", strip.white = TRUE)
meta20 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(20).tsv", sep = "\t", strip.white = TRUE)
meta21 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(21).tsv", sep = "\t", strip.white = TRUE)
meta22 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(22).tsv", sep = "\t", strip.white = TRUE)
meta23 <- read.csv("Data/genetic_data/GISAID_complete_highcoverage_20210107/gisaid_hcov-19_2021_01_07_16_(23).tsv", sep = "\t", strip.white = TRUE)

**Comment by BernardoGG** [comment]
These were downloaded directly from GISAID when the FASTA files were downloaded. I've added two files as examples in the [`metadata`](https://github.com/BernardoGG/SARS-CoV-2_Genomic_lineages_Ecuador/tree/master/Data/genetic_data/metadata) directory, mostly as a reference of the file structure. It should be noted that in that same directory there is a file named GISAID_hCoV-19_20210107_EC_all.tsv, this file contains the information produced by the referenced code. The reason why it was originally imported into the R working environment as separate files is that GISAID only allowed for a limited number of sequences to be downloaded at any one time.

**Comment by BEAST-Community** [comment]
thanks, i like your research very much. Thanks for your help.
